kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  environment:
    CONFIG:
      from_secret: ensaas_config
    ENSAAS_USER:
      from_secret: ensaas_username
    ENSAAS_PASSWORD:
      from_secret: ensaas_password
  settings:
    repo: ensaas/k8s-routines
    username: ensaas
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.4.2
    build_args_from_env:
      - CONFIG
      - ENSAAS_USER
      - ENSAAS_PASSWORD

- name: deploy
  image: ensaas/k8s-routines
  commands:
  - kubectl config use-context $CURRENT_CONTEXT
  - kubectl config set-context --current --namespace=$NAMESPACE
  - kubectl get deploy | grep k8s-routines && kubectl delete -f k8s/
  - kubectl apply -f k8s/
  environment:
    CURRENT_CONTEXT: 6e0745d0-5c25-11ea-b898-fa99721571bc-eks004
    NAMESPACE: devspace

# - name: deploy
#   image: danielgormly/drone-plugin-kube:0.0.1
#   settings:
#     template: k8s/deployment.yaml
#     ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVIakNDQWdhZ0F3SUJBZ0lVWkFJUnJ4b2RHclo5YTk0TkpMeEkvcDhpRjM4d0RRWUpLb1pJaHZjTkFRRU4KQlFBd0RURUxNQWtHQTFVRUF4TUNZMkV3SGhjTk1qQXdNekF5TURFeU5qQXdXaGNOTWpFd016QXlNREV5TmpBdwpXakF2TVMwd0t3WURWUVFERXlRMlpUQTNORFZrTUMwMVl6STFMVEV4WldFdFlqZzVPQzFtWVRrNU56SXhOVGN4ClltTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETlFUMzZRWXZ6cUNyc0ZmbjUKMkpJZ1JwTjdRODliSE9yRjlzWE5DcDd3SUc5SnJlK1hzc0cxSlBramlsbFN3OWhPUHVSemhxZ1NTaEhONUNWeApqT09OWkN6Q1ozR2lNdU9UUS91cmxWaDNydmR5WGZaVmpkUEYzQU43Y2xvb0VSWWxUWEl1QUVBbURKbU5EQTBIClBnUURTNmIzUHR3N2c2OHk4b0dycjVZN1p5d3lTa2E5STQzb2twUFI5UHh5ZUVJaHRLem9idXI5T0hUYTUvSEYKUGUxeGVIbTMvNGM2dXRNb0RoTEpTYWpiTm43aCthUlF3cS85RWlpTEsyQWE1Z1Rzb3B3R2drZGtZQUJBeGlTUwpOa0RoVmpiVHl1VTZ2VXNIY1VRVEFFS1B2V1hsWDd4ekQ3cTBYVm9ZWjg0UGlQQmtJMVNWczFjeldOMlFqaExIClprSHRBZ01CQUFHalZEQlNNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0QKQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlN6dlJsMGVid2M0aVFYQnRFVXc3UkJDWmdFRlRBTgpCZ2txaGtpRzl3MEJBUTBGQUFPQ0FnRUFDQnhLZzFTVWpOcWJITXEzZnBVWkFYUHdTK1haQ3UwVVlSemc1RTZvCm9pYkxKY3dMSzFQWk5IN0oreXI3NlozY0dveHZnMFFZTmFDT3N4NSt4dXZubGdGdFR1eE9PUUllNkRwVDlLWG8KQmdlRDdIM1JIYS9uOGxjbXFvSDlqTzYvME5ueHN0MnZXeGV2WDVPMzkvZGtlRWo1UFJSTlo5bWg1bW9IOWNiOApTTkU2K3h4ZVVxbWp0RE1EelJscUViRWUyYXhpRHlCZmxaVFFMVDIvM0lLRkhrZDNLZjhrMVFWZWNEd21PNkEzCjZQWDZIdUtrSkxwN3F1enhQUW50aFBudXBaeHduN2sycmtzQjhqYzZSM0cweVp1S21XaS9ETkxXM1ZoVjU1U3UKbmtkWmtVVjFuVVViV1dyLzltZmJsV1AvZ1VKNk9GckVJbTlBd1k5cGtTdG5RRnVyZ2s3MzF5V1QxTmVpdFMvTgoxZXhYK2NUN3dWNDVTSkJZcC9uSFVmWjVPOGVONjJ3ZE5BQmQ3RGpUZmJhV2kwT2VKUTlYYnA3TnF6clFqNHp5CnUrdnlneG9Cclg2SHVTRkNTdnNqMDdJMEtqMFdsaTZGcW5HejB4eXl5OFloeWRvRWFNcFlDb3JheExha1hGVUIKZmM0L2JqQXIvenR5VDl4My9ldlIrRDJHL2JKVTdhbzdkc0x3YmJYLzhjZ204TDYvbVlFcTIyem8ydXdwVzF3cgpRRUJaMmxHYnV4bWp6S2c3UU1CNS90bFk2ckU2dWc2VmlNRzFjZXN6bERiTlEvQUxQd0VQQTNNS200U3dMN3ArCkh4QTdtQk5Nam5SQ2h2WW1tdzRPVTNGcDNjcDFEb01oWWRkR1g1a1BDZkpVRm4xNS9QS1N4NVFRQlBkRjZYRUkKWlJzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#     server: https://ensaas-eks-ensaas-40-3e4c4b-8f71261c.hcp.southeastasia.azmk8s.io:443
#     token:
#       from_secret: k8s_token