kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: ensaas/k8s-routines
    username: ensaas
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.2.4