kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  environment:
    CONFIG:
      from_secret: ensaas_config
    ENSAAS_USER:
      from_secret: ensaas_username
    ENSAAS_PASSWORD:
      from_secret: ensaas_password
  settings:
    repo: ensaas/k8s-routines
    username: ensaas
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.7.1
    build_args_from_env:
      - CONFIG
      - ENSAAS_USER
      - ENSAAS_PASSWORD

- name: deploy
  image: ensaas/k8s-routines
  commands:
  - kubectl config use-context $CURRENT_CONTEXT
  - kubectl config set-context --current --namespace=$NAMESPACE
  - kubectl get deploy | grep k8s-routines && kubectl delete -f k8s/
  - kubectl apply -f k8s/
  environment:
    CURRENT_CONTEXT: 6e0745d0-5c25-11ea-b898-fa99721571bc-eks004
    NAMESPACE: devspace
