kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
    - echo $PASSWORD | docker login --username $USER --password-stdin
  environment:
    USER: ensaas
    PASSWORD:
      from_secret: docker_password
