kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  environment:
    CONFIG:
      from_secret: ensaas_config
    ENSAAS_USER:
      from_secret: ensaas_username
    ENSAAS_PASSWORD:
      from_secret: ensaas_password
  settings:
    repo: ensaas/k8s-routines
    username: ensaas
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.4.2
    build_args_from_env:
      - CONFIG
      - ENSAAS_USER
      - ENSAAS_PASSWORD

# - name: deploy
#   image: ensaas/k8s-routines
#   commands:
#   - kubectl config use-context $CURRENT_CONTEXT
#   - kubectl config set-context --current --namespace=$NAMESPACE
#   - kubectl get deploy | grep k8s-routines && kubectl delete -f k8s/
#   - kubectl apply -f k8s/
#   environment:
#     CURRENT_CONTEXT: 6e0745d0-5c25-11ea-b898-fa99721571bc-eks004
#     NAMESPACE: devspace

- name: deploy
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://ensaas-eks-ensaas-40-3e4c4b-8f71261c.hcp.southeastasia.azmk8s.io:443
    kubernetes_token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZXZzcGFjZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTRwNmY1Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwMmMzZjA5Ny05N2RmLTQwYzMtYWNjNS0xNjA2MWE5NzI4NzQiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2c3BhY2U6ZGVmYXVsdCJ9.OjCLHNahr1irbNwmR-w-C_Y2emrqYl6NFvtLoPXkAd6injWh4eoIp3J3Ir7-Buimm-NhmXRDdbf37YFtBVbqeqJbqDkXrd2sm1FAVCCOpXpwvWPGWHdV8o2qrVQEt-HN689X2Lvb5QKOcfTFomTHDyjBzhbFKU4yFoXHfysfMnwuyJnaVqDdorSGsGLk1Cp4OrhkrGRGyIonnPf1aqxKhgf1-xirZcJGB45EklpXglCPIuOZKXFC7wo37XpY5IcNR5s52ql_QTAzrvQuEt2xNdbJC8so6ATx05de7mtHyJZePhKqDw0cX48yNDzzP0OFKOiHc8RvXIv0Yw_C8dYiKyhobb5ZIlIyXdj3EfyDaKg3mNZf-AWwJ_hu4kpLQXgQRWINEd1DnO985e-haY3B6RosZP3_GpIqT3nLfY8lHOgZIKR6t5UEGgV-i-gdjlcsPECkEAZt9Ht0SmPWEKke8KWLAtRceRLByU3CoMmOgDXjn4d1i09mKav21DXALkKkYAxFOfUDETckYEGLfLcJuKeYcf2NoZwSIk_rAx7mL66v85NGpXd2hVdaJovD6N3dW1Qg8YpEwet_WQjh3HgKkHYwyWMXHwqjFXyacuMFSVlvQLGIdLFrrGqGIuetX2QgKkWobAcIqgeK_Bdlf2-2F01LVG4m8m_tWZDwQyGf8wU
    namespace: devspace
    deployment: k8s-routines
    repo: ensaas/k8s-routines
    container: routines
    tag: 0.4.2