#!/bin/sh

RESPONSE=$(curl -X POST https://andruxnet-random-famous-quotes.p.rapidapi.com/ \
                -d "cat=famous&count=1" \
                -H "x-rapidapi-host: andruxnet-random-famous-quotes.p.rapidapi.com" \
                -H "x-rapidapi-key: 33c9529002msh67b66ec4cf40d06p1ac0b7jsn0bd10bb27d8e")

QUOTE=$(echo $RESPONSE | jq .[0].quote)
AUTHOR=$(echo $RESPONSE | jq .[0].author | tr -d '\"')

MESSAGE="%0D%0A\
$QUOTE%0D%0A%0D%0A\
- $AUTHOR"

# Sending LINE Notify
curl -H "Authorization: Bearer $LINE_NOTIFY_TARGET" -d "message=$MESSAGE" -X POST https://notify-api.line.me/api/notify; echo
