#!/bin/sh

response=$(curl -X POST https://andruxnet-random-famous-quotes.p.rapidapi.com/ -d "cat=famous&count=1" -H "x-rapidapi-host: andruxnet-random-famous-quotes.p.rapidapi.com" -H "x-rapidapi-key: 33c9529002msh67b66ec4cf40d06p1ac0b7jsn0bd10bb27d8e")

quote=$(echo $response | jq .[0].quote)
author=$(echo $response | jq .[0].author | tr -d '\"')

MSG="%0D%0A\
$quote%0D%0A\
%0D%0A\
- $author
"

# Sending LINE Notify
curl -H "Authorization: Bearer $LINE_NOTIFY_TARGET" -d "message=$MSG" -X POST https://notify-api.line.me/api/notify; echo
