#!/bin/sh

RESPONSE=$(curl -X POST http://api.forismatic.com/api/1.0/ \
                -d "method=getQuote&key=123&format=json&lang=en")

QUOTE=$(echo $RESPONSE | jq .quoteText)
AUTHOR=$(echo $RESPONSE | jq .quoteAuthor | tr -d '\"')

MESSAGE="%0D%0A\
$QUOTE%0D%0A%0D%0A\
- $AUTHOR"

# Sending LINE Notify
curl -H "Authorization: Bearer $LINE_NOTIFY_TARGET" -d "message=$MESSAGE" -X POST https://notify-api.line.me/api/notify; echo
