#!/bin/sh

CMD_COUNT_DEPLOY="kubectl get deploy | sed '1d' | wc -l | sed 's/[[:space:]]//g'"
CMD_COUNT_POD="kubectl get pod | sed '1d' | wc -l | sed 's/[[:space:]]//g'"

# Cleaning
cleanup () {
    # Count the quantity of current objects before cleaning
    DEPLOY_BEFORE=$(eval $CMD_COUNT_DEPLOY)
    POD_BEFORE=$(eval $CMD_COUNT_POD)

    export RESULT=$(kubectl get deploy | grep 0/ | awk '{print $1}')
    kubectl delete deploy $(echo "$RESULT"); sleep 1
    kubectl delete svc $(echo "$RESULT"); sleep 1
    kubectl delete ing $(echo "$RESULT"); sleep 1
    kubectl delete pod $(echo "$RESULT"); sleep 1
    kubectl delete rs $(echo "$RESULT"); sleep 1
    kubectl get deploy | grep 0/ | awk '{print $1}'; sleep 1
    kubectl delete deploy $(kubectl get pod | grep -v Running | sed '1d' | cut -d'-' -f1,2,3)
    sleep 5

    # Count again after cleaning
    DEPLOY_AFTER=$(eval $CMD_COUNT_DEPLOY)
    POD_AFTER=$(eval $CMD_COUNT_POD)

    DEPLOY_DIFF=$((DEPLOY_BEFORE - DEPLOY_AFTER))
    POD_DIFF=$((POD_BEFORE - POD_AFTER))

    MESSAGE="\
    - deployments removed: $DEPLOY_DIFF%0D%0A\
    - pods removed: $POD_DIFF\
    "

    append_message
}

switch_context_ns () {
    kubectl config use-context $CONTEXT
    kubectl config set-context --current --namespace=$NAMESPACE
}

append_message () {
    MESSAGE_NOTIFY="$MESSAGE_NOTIFY%0D%0A$MESSAGE"
}

# Initial message
MESSAGE_NOTIFY="%0D%0AJust finished checking if any bad pods."

# ------ sa-eks004-level2 ------
DATA_CENTER="sa"
CLUSTER="eks004"
NAMESPACE="level2"
CONTEXT="6e0745d0-5c25-11ea-b898-fa99721571bc-eks004"

# Adding title
MESSAGE="[$DATA_CENTER-$CLUSTER-$NAMESPACE]"
append_message

# Do the cleanup
switch_context_ns
cleanup

# ------ hz-eks006-level2 ------
DATA_CENTER="hz"
CLUSTER="eks006"
NAMESPACE="level2"
CONTEXT="24c3c1e0-8094-11ea-a8cd-d6940539dde2-eks006"

# Adding title
MESSAGE="[$DATA_CENTER-$CLUSTER-$NAMESPACE]"
append_message

# Do the cleanup
switch_context_ns
cleanup

# LINE Notification
curl -H "Authorization: Bearer $LINE_NOTIFY_TARGET" -d "message=$MESSAGE_NOTIFY" -X POST https://notify-api.line.me/api/notify; echo
